### ISSUE TITLE
CHARTS: Remove the extra data tables from the charts

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/secureDiaLog#10]
# Description

Remove the empty tables for the extra daily observations from the charts.

# Why

When there is no data it looks very odd and only gets displayed when the tooltip is activated. Perhaps remove them from the charts. The data can be viewed in the table within the DATA page.

# Closing Criteria

- [ ] No longer display the addition daily observations.

![Image](https://github.com/kimishidairessha/secureDiaLog/assets/1681429/b5a088b7-fb75-4e1e-b304-9ca97787a4d3)

**Comment by kimishidairessha** [comment]
I think it is useful for users to display the data of the day. The charts only show the maximum values of the data. However, for some data, such as blood glucose value, which may fluctuate within a day, it is not intuitive to find an indicator in the Table. So I keep this feature, but to solve the problem that the detailed data at the bottom may confuse the user, I sync the FlTouchEvent settings with the tooltip display.
