### ISSUE TITLE
APP: Remove all of the trace print/debugPrint statements

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/secureDiaLog#11]
# Description

Remove the debugging/tracing print() and debugPrint() statements. Keep the debugPrint() statements that are useful for debugging, but not those that have already been debugged.

# Why

To keep the code clean, and to reduce the output so the user is not concerned about so many 'unexplained' messages.

# Closing Criteria

- [ ] Minimal, if any, print output.

**Comment by kimishidairessha** [comment]
For this problem, getSurveyDayInfoList function is being called more than once in the code. It is not a bug.


![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/83d89b96-cf87-4e61-b7c4-8f911e5e33bf)

**Comment by kimishidairessha** [comment]
Delete prints for tests.
