### ISSUE TITLE
APP: Add conditional debugPrint()

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/secureDiaLog#12]
# Description

Replace all `print()` with `debugPrint()`.

debugPrint() should be used for printing debugging or trace information to the terminal. There is a simple trick to have it conditional (see https://github.com/gjwgit/rattleng/blob/main/lib/main.dart). Use that here so we can easily turn debugPrint() off.

**Note:** debugPrint() should be used for printing messages about what the app is doing in a debugging kind of way. Use GUI popups for errors that occur.

# Why

To easily remove debugPrint() messages from a running app.

# Closing Criteria

- [ ] debguPrint() messages are not displayed if turned off

**Comment by kimishidairessha** [comment]
Replace all print() with debugPrint(). And allow debugPrint() behaviour to be controled from the environment.
