### ISSUE TITLE
CHARTS: Add left/right edge space

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/secureDiaLog#13]
# Description

Add a gap between the charts and the edge of the app - left and right.

# Why

The charts will look better if they are not flush to the edge of the app.

# Closing Criteria

- [x] There is a gap left/right between the chart and the edge of the app.

**Comment by kimishidairessha** [comment]
Since charts is slippable, it doesn't always have gaps on either side of the screen. When sliding to the initial position or the termination position, there is a gap on both sides of the screen.
