### ISSUE TITLE
CHARTS: Date format options

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/secureDiaLog#14]
# Description

Change the x-axis data labels to something like `24 Oct` rather than `2023\n10-24`

# Why

The charts don't need the year because (currently) they only show current data. The format `24 Oct` is quicker for a person to parse than `10-24` and is not ambiguous.

# Closing Criteria

- [ ] Updated and simplified date formats in the charts.

**Comment by kimishidairessha** [comment]
![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/c9493d39-08cf-42e8-8d43-d93125a31e21)
