### ISSUE TITLE
CHARTS: Use same background colour as the DATA table

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/secureDiaLog#16]
# Description

Use the same background colour for the charts and the data table. Be sure to have it as a constant in lib/constants/app.dart.

# Why

So that the app colours are consistent.

# Closing Criteria

- [ ] DATA and CHART backgrounds are the same colour.

**Comment by kimishidairessha** [comment]
Change bg color of both charts and table to yellow[50].


![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/49c8065d-424a-4bce-b374-2cb73b951dab)
