### ISSUE TITLE
Configure the app to also work in a dekstop/web profile

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/secureDiaLog#17]
# Description

The current app assumes target is a mobile phone. But it will also run on desktops and in web browsers. Configure dynamic layout so that the app also works well in an app size of 950 wide by 600 high.

# Why

So that a user can run the app on any platform, which is an advantage of using flutter.

# Closing Criteria

- [ ] App looks good and works `naturally` on any platform

**Comment by kimishidairessha** [comment]
fix ui including text color of buttons and background for win and web.
