### ISSUE TITLE
SETTINGS: Add date of last survey

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/secureDiaLog#18]
# Description

Include the data/time of the most recent survey in the settings page. This can not be edited in settings but is useful to have it visible somewhere. We might move it somewhere else later.

# Why

So that we can see the date of the last survey somewhere in the APP.

# Closing Criteria

- [ ] Date of the last survey is visible in the app.

**Comment by kimishidairessha** [comment]
![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/66b9635a-6aae-49b5-917a-a3dca3b8c521)
