### ISSUE TITLE
ENCRYPTION SCREEN: Do not show the encryption screen if the key has already been stored locally

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/secureDiaLog#20]
# Description

If the encryption key has been obtained from local storage do not show the Encryption key page after authenticating. Go straight to the Home screen. 

# Why

The Encryption key page seems redundant if it has already been retrieved from local secure storage.

# Closing Criteria

- [ ] Skip the encryption key screen if it is already available.

**Comment by kimishidairessha** [comment]
If the key stored in the device is correct, then skip key page. If it is incorrect:


![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/aeb1f2c4-4210-47b1-b2b3-8d5d73fe2282)
