### ISSUE TITLE
WEB: Charts seem to display data from 1 week ago

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/secureDiaLog#28]
# Description

The `flutter build web` and `flutter run -d chrome` versions of the app seem to display data from 1 week ago in the charts?

Web/chrome versions:

![Image](https://github.com/kimishidairessha/secureDiaLog/assets/1681429/bf24e156-a17f-4733-bb8b-60155b4db378)

Compared to desktop version:

![Image](https://github.com/kimishidairessha/secureDiaLog/assets/1681429/81e75060-8eac-459b-a760-3eb9d72b6e0c)

**Comment by kimishidairessha** [comment]
I tried this method but it still doesn't work for web.
https://docs.flutter.dev/release/breaking-changes/default-scroll-behavior-drag

class MyCustomScrollBehavior extends MaterialScrollBehavior {
  // Override behavior methods and getters like dragDevices
  @override
  Set<PointerDeviceKind> get dragDevices => {
    PointerDeviceKind.touch,
    PointerDeviceKind.mouse,
    // etc.
  };
}
return Column(
      children: [
        ScrollConfiguration(
            behavior: MyCustomScrollBehavior(),
          child: SingleChildScrollView(
            controller: scrollController,
            scrollDirection: Axis.horizontal,
            child: Container(
              color: Constants.tableColor,
              child: SizedBox(
                height: 200,
                width: 38 * rawBarGroups.length.toDouble(),
                child: BarChart(
                  BarChartData(
                  maxY: 10,
                  barGroups: visibleBarGroups,
                  barTouchData: BarTouchData(
                    touchCallback:
                        (FlTouchEvent event, BarTouchResponse? touchResponse) {

**Comment by kimishidairessha** [comment]
Unlike phones, the screen on the WEB is large enough that I eliminated horizontal scrolling on the WEB and kept it on Android.

![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/b12a63bc-716c-4369-89f4-322c2703ce2a)

![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/348128c4-9f20-48fa-af1c-28b22b678061)
