### ISSUE TITLE
DATA PAGE: Add Import from CSV to load the data from a CSV file

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/secureDiaLog#3]
# Description

Together with Export to CSV and a delete option this could be a simple way to "edit" the data and to backup and restore the data.

**Comment by kimishidairessha** [comment]
Import from CSV and store the data in the Pod. For example: 1. CSV from the device or online.


![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/679ef602-c138-410f-98ef-2377f889728f)


![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/e043b411-bc66-4099-9033-899cf83eb909)


2. Add the data in the Pod.


![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/87b8b64f-0679-4fcb-827e-3b0d11a28c2a)



![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/639cbb9a-8f66-46e1-82b9-25689cda4deb)
![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/e6e4a2e0-f002-4c98-a41a-046fe41577b1)
