### ISSUE TITLE
WEB: Currently not displaying charts or data

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/secureDiaLog#35]
When visiting https://ecosysl.net/secureDiaLog/

![Image](https://github.com/kimishidairessha/diabetes/assets/1681429/7e3a3e99-1824-48a1-b238-7721066a8b8d)

**Comment by kimishidairessha** [comment]
It works fine using my link. Could you please show your POD information?


![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/941895a1-e90d-4c4b-89c1-7afc79e1714a)



![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/870002f9-c506-4b1d-80bd-67fde8a3544e)

**Comment by gjwgit** [comment]
It seems that this happens when there is no secureDiaLog folder on the server.
