### ISSUE TITLE
EXPORT: Provide a default filename like dialog_20231215.csv

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/secureDiaLog#41]
# Description

It is handy to have a default file name provided which a user can override if desired. I like the names perhaps like `dialog_yyyymmdd.csv`.

# Why

So that a user does not have to provide their own file name every time.

![Image](https://github.com/kimishidairessha/secureDiaLog/assets/1681429/39c8968b-bcb0-47b1-953a-66489fee3305)

**Comment by kimishidairessha** [comment]
![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/5979448c-ab98-4e20-b681-2d7e03fd1129)



![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/f1dba84e-c4db-4116-b8a0-776971a67299)

**Comment by gjwgit** [comment]
Shouldn't the filename be displayed here in the popup and then I can change it?

**Comment by gjwgit** [comment]
When I now click on Export in the above screenshot, to which folder is the file saved?
