### ISSUE TITLE
EXPORT: chrome export adds extra .csv

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/secureDiaLog#43]
# Description

I specified to save the file `a.csv` and the actual file saved to `a.csv.csv`. Best to check if the filename already has a `.csv` before adding another one.

# Why

So that the user can type .csv or not and all works as expected.

**Comment by kimishidairessha** [comment]
![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/08fe9960-b7a9-4c19-88e9-bb6b08fe82f2)



![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/39821bd6-7056-466f-802b-762fda7df569)

**Comment by gjwgit** [comment]
Code looks okay, but can't test at present without Linux support.
