### ISSUE TITLE
LAYOUT: Improve settings layout for desktop/browser

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/secureDiaLog#47]
# Description

Improve the layout of the SETTINGS page for desktop (including browser) dimensions.

# Why

So that the user experience on the desktop is just as good as for mobile.

# Details

Suggestions include:

- [ ] The toggle switch should be next to the "Capture Location"
- [ ] The LOGOUT button should not expand so much and be aligned on the left.

![Image](https://github.com/kimishidairessha/secureDiaLog/assets/1681429/1b7941c6-ee54-463d-ab3c-e1f34a9a6d7a)

**Comment by kimishidairessha** [comment]
![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/221202ce-ad40-491a-abbe-c0eba464c3cb)
