### ISSUE TITLE
LAYOUT: Improve the layout on the survey page for desktop/browser

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/secureDiaLog#48]
# Description

Improve the layout of the SURVEY page for desktop (including browser) dimensions.

Visit https://securedialog.solidcommunity.au/

# Why

So that the user experience on the desktop is just as good as for mobile.

# Details

Suggestions include:

- [ ] The "lacking in strength today?" should not expand to the whole width - just to a mas width
- [ ] The SUBMIT button should not expand so much and be aligned on the left.

![Image](https://github.com/kimishidairessha/secureDiaLog/assets/1681429/a9a9d619-9dbd-4026-b8fc-7a6f660bd235)

**Comment by kimishidairessha** [comment]
![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/f2b9a1df-6921-425b-a584-e9c87402983a)
