### ISSUE TITLE
BUG: After clicking the SURVEY button it takes quite a while for the survey to appear

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/secureDiaLog#49]
# Description

On clicking the survey button it takes a few seconds on the web version and there is a noticeable lag on the desktop version. Why is there a lag and can it be avoided. If it really can't be avoided show a busy icon so the user knows it has not frozen.

# Why

So that the user experience is improved.

**Comment by kimishidairessha** [comment]
Add loading icon #63
