### ISSUE TITLE
CHARTS PAGE: For the popups show int not double values

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/secureDiaLog#5]
# Description

Show the data in the tooltips as integers. Also on the DATA PAGE show the data as integers unless you expect the numbers to actually be double.

# Why

A good practice for presenting data is to show accuracy to what is required. Thus showing heart rate or diastolic as '82.0' is bad practice - the '.0' adds no information if the data is collected as integers and can be misleading!

![Image](https://github.com/kimishidairessha/secureDiaLog/assets/1681429/b1295613-3c5e-476a-84e2-29e903fad0a2)
![Image](https://github.com/kimishidairessha/secureDiaLog/assets/1681429/44f96a30-5892-41cb-99c7-1a6dc7370562)

**Comment by kimishidairessha** [comment]
![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/f026ec53-1578-4534-a38e-419231c531f0)
