### ISSUE TITLE
LAYOUT: Reduce the width of the START NOW and the LOGOUT buttons onto one line

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/secureDiaLog#53]
# Description

Do not expand the buttons more than a max width. And place the buttons on the one line.

![Image](https://github.com/kimishidairessha/secureDiaLog/assets/1681429/eca3896d-fce8-4080-940a-2d106edfeea7)

**Comment by kimishidairessha** [comment]
![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/1bd55953-d8e9-457f-88b2-3abb8b04b0ab)
