### ISSUE TITLE
DATA EXPORT IMPORT: An import does not display

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/secureDiaLog#55]
# Description

An import does not seem to cause the charts to be updated with the new data.

After an IMPORT I can see:

![Image](https://github.com/kimishidairessha/secureDiaLog/assets/1681429/04e61bd0-acf9-4c8a-80bf-900be400e303)

But in CHARTS there is no display?

![Image](https://github.com/kimishidairessha/secureDiaLog/assets/1681429/0bff9f03-1804-474f-807a-37695579dd74)

This should be updated without the need to click the RELOAD button? Flutter should be watching the data and be notified when the data is updated so that the display gets updated when it rebuilds the page. This might need to use RiverPod?

**Comment by kimishidairessha** [comment]
When the import or delete action is completed in HomeData, HomeProfile page will refresh. Use Provider to implement this action.
